eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: PDC2-L-138LY4D.dir.svc.accenture.com
    prefer-ip-address: true
